### ISSUE TITLE
最新版本没有开源么

### ISSUE THREAD

**Issue by cqjjjzr** [zyzsdy/biliroku#1]
GitHub上版本低于程序版本1.4啊。。。

**Comment by zyzsdy** [comment]
一直忙着没有时间更新，已知bug也拖了四个月真是不好意思。
刚刚一群的人要录南鹿于是被催着更新了。。。

顺便也推一下这里，现在也更新到1.4.1源码了。
感谢支持，我期待着pr哦。

**Comment by cqjjjzr** [comment]
结果我已经用java重写了整个程序2333有时间再pr吧，我的设想是完全模块化，然后就可以增加很多功能，比如边拉流边编码保存什么的w

**Comment by robinWongM** [comment]
关于那个边录边保存弹幕的，有一个问题是：
当网络不好的时候，就容易出现 下载用时 与 视频实际时长 不符的情况，也就导致弹幕时间轴与实际视频错位
这边的一个小建议：如果要解决这个问题的话可能需要复杂一点，比如用ffmpeg实时解码流获取时间，或者干脆直接加入视频播放功能，也就不用一边开网页版直播一边用BiliRoku下载，虽然这样子可能并非BiliRoku的本意？

**Comment by zyzsdy** [comment]
其实你在B站看直播也是会出现这个问题的。
现在我里面有个mediainfo.dll可以解出来视频实际时长，弹幕里面是自带发出时间的。

**Comment by husy8** [comment]
弱鸡问下这个要导入到VS里自己编译么……

**Comment by zyzsdy** [comment]
要的。。我csproj和sln可以没加入到代码库里。。等我加一下。
用VS2015打开sln

**Comment by husy8** [comment]
好的，麻烦啦
