### ISSUE TITLE
快速点击开始/停止按钮后程序会崩溃

### ISSUE THREAD

**Issue by zyzsdy** [zyzsdy/biliroku#11]
如题，稳定复现。

如果出现同样问题的用户请不要点击那么快。
我想想这问题怎么处理。

**Comment by 0x7A2C9E5D** [comment]
这个要修改源代码才能解决

**Comment by zyzsdy** [comment]
你这个回复我竟无言以对

**Comment by Last-Order** [comment]
个人认为这里应该是程序相关代码出了问题。

**Comment by lautis0503** [comment]
System.NullReferenceException was unhandled
Message: An unhandled exception of type 'System.NullReferenceException' occurred in mscorlib.dll
Additional information: Object reference not set to an instance of an object.

Downloader.cs => CheckStreaming => _flvDownloader = null
