### ISSUE TITLE
-

### ISSUE THREAD

**Issue by mlisry** [zyzsdy/biliroku#12]
-

**Comment by zyzsdy** [comment]
请提供详细的信息以及出错记录。

我这里测试是正常的。

**Comment by mlisry** [comment]
主播未直播时点击开始按钮，
主播直播后无法自动开始录播。。

**Comment by lautis0503** [comment]
@mlisry 
可能网络原因，试试
https://github.com/zyzsdy/biliroku/blob/master/BiLiRoku/Bililivelib/Downloader.cs#L106
增加等待时间，单位毫秒

**Comment by mlisry** [comment]
ww
