### ISSUE TITLE
非常好用。就是有一个小问题

### ISSUE THREAD

**Issue by najloa** [zyzsdy/biliroku#18]
问题是，如果主播网络不稳定经常断线，那么这个软件的断线重连就会无效(至少我这里是这个情况)，传输大小会一直不见增长（主播状态也一直保持在：正在直播）。我希望作者能改进一下检测方式，比如说10秒定时检查文件大小，如果体积不增加就停止，重连。

**Comment by zyzsdy** [comment]
与#25 重复。
