### ISSUE TITLE
获取真实视频地址的方法的疑问

### ISSUE THREAD

**Issue by kobayashikanata** [zyzsdy/biliroku#19]
在BiliRoku.Bililivelib中的PathFinder类的方法GetTrueUrl(roomId)中，
这个获取真实视频地址的方法，向以下地址发送了一些不影响程序的信息
$"https://zyzsdy.com/biliroku/stat?os={osVer}&id={roomid}&ver={appVer}"
在我猜测用于统计的前提下，我想问一下，这个用途是什么?

**Comment by zyzsdy** [comment]
单纯的用于统计。
至于用途其实有许多种，但是我主要还是看新版本会不会出现大量的针对同一roomid的短时间重复访问。出现那样的状况说明版本出了些问题。
所以我也不需要更多信息，统计数据就是包括这三项内容：操作系统代码、目标房间号、版本号。

如果你还是觉得不安全的话，完全可以fork并去掉这行代码，编译自己的版本使用。
甚至你可以简单的使用host把zyzsdy.com屏蔽掉，统计信息提交失败不会影响程序的运行。
