### ISSUE TITLE
1.5.0 不能用了

### ISSUE THREAD

**Issue by bojiwama** [zyzsdy/biliroku#21]
显示未直播

**Comment by lautis0503** [comment]
https://github.com/zyzsdy/biliroku/issues/12#issuecomment-301753926

**Comment by zyzsdy** [comment]
请提供更多的信息，如果有可能的话说明一下操作系统版本、尝试录制的时间、以及尝试录制的直播间号，贴一下出问题的时候右侧日志列表显示的消息。

最近发现部分用户有类似情况，然而有时候出现有时候没有问题，现在不好确认是不是B站还隐藏着一个不同的api？是我们的实现有问题？还是仅仅是网络问题。

**Comment by harryzyj** [comment]
![2017-11-23_230442](https://user-images.githubusercontent.com/33753242/33178961-ce5a20d2-d0a2-11e7-8e67-a66505c37867.jpg)
所有直播间都这样
系统win10（这两天升级的最新的那个版本和之前的那个版本没变化）
尝试录制时间2017年11月23日23点
使用上海电信网络
b站改版之前使用1.48（好像是这个版本）还是很好用的

**Comment by bojiwama** [comment]
@zyzsdy 发现问题了，原因是开启了代理软件（Psiphon 3），软件自动开启并设置了系统的代理，关闭系统代理就能正常录制了

**Comment by zyzsdy** [comment]
暂时没有后续问题发现

**Comment by kevinluo6188** [comment]
#12
