### ISSUE TITLE
最近录制经常出现空文件请问怎么解决

### ISSUE THREAD

**Issue by tx4806** [zyzsdy/biliroku#22]
软件版本1.50
系统版本WIN7 
有安装360间谍大师
录制直播间号20463
右侧Log：没有保存。
出现的问题：生成的视频文件大小只有0字节，有文件 但是视频无内容只有一个空文件 弹幕文件无内容。
录制方式：午夜用公司电脑挂机录制视频（无人值守）

**Comment by zyzsdy** [comment]
It's a feature.
设计如此。

我啥时候再提供个功能帮你清掉那些0字节文件吧。
