### ISSUE TITLE
录制的视频大小为0字节

### ISSUE THREAD

**Issue by huqinpku** [zyzsdy/biliroku#25]
软件挂了大约一个星期吧，Log显示基本每天都有直播，但录制的视频多数都是0字节，以前偶尔有录成功的，但最近没有过。。。

选项中选择了“同时保存弹幕”和“等待主播推流后自动开始”

[INFO 09:19:56] 启动成功。
[AutoUpdate 09:19:56] 检查更新。
[AutoUpdate 09:19:56] 当前已是最新版本。
[INFO 09:19:59] 尝试获取真实房间号
[INFO 09:19:59] 真实房间号: 491683
[INFO 09:19:59] 地址解析成功：https://live-play.acgvideo.com/live/578/live_26633150_2634870.flv?wsSecret=dbd25cf2c9aa76ea07d6d359f826a310&wsTime=5a5b9f4f
[INFO 09:20:00] 开始解析弹幕服务器
[INFO 09:20:00] 解析弹幕服务器地址成功：livecmt-2.bilibili.com
#### [INFO 07:43:02] [主播开始直播]
[INFO 07:43:02] 地址解析成功：https://live-play.acgvideo.com/live/938/live_26633150_2634870.flv?wsSecret=6f3d86e6a79d5a6fc8d6992180e048f3&wsTime=5a5e2b96
[INFO 07:43:02] 下载地址已更新。
[INFO 08:27:20] [主播结束直播]
[INFO 07:34:11] 连接断开
[INFO 07:34:11] 弹幕服务器断开
[INFO 07:34:11] 尝试重新连接弹幕服务器
[INFO 07:34:11] 开始解析弹幕服务器
[INFO 07:34:12] 解析弹幕服务器地址成功：livecmt-2.bilibili.com
#### [INFO 05:10:51] [主播开始直播]
[INFO 05:10:52] 地址解析成功：https://live-play.acgvideo.com/live/399/live_26633150_2634870.flv?wsSecret=9e5b4ffc040f79dfebabdbb937468853&wsTime=5a60aaed
[INFO 05:10:52] 下载地址已更新。
[INFO 07:29:34] [主播结束直播]
#### [INFO 00:38:20] [主播开始直播]
[INFO 00:38:21] 地址解析成功：https://live-play.acgvideo.com/live/465/live_26633150_2634870.flv?wsSecret=90e3b65ac76bb0fc07362ca3f6edbe3d&wsTime=5a61bc8c
[INFO 00:38:21] 下载地址已更新。
[INFO 02:04:13] [主播结束直播]
#### [INFO 04:15:10] [主播开始直播]
[INFO 04:15:11] 地址解析成功：https://live-play.acgvideo.com/live/887/live_26633150_2634870.flv?wsSecret=c6ffe253ea1354046eacf7414b989996&wsTime=5a61ef5f
[INFO 04:15:11] 下载地址已更新。
[INFO 06:57:48] [主播结束直播]
#### [INFO 04:17:53] [主播开始直播]
[INFO 04:17:53] 地址解析成功：https://live-play.acgvideo.com/live/283/live_26633150_2634870.flv?wsSecret=5678ef3b3ba20c71f29e13faba8771bc&wsTime=5a634180
[INFO 04:17:53] 下载地址已更新。
[INFO 05:52:32] [主播结束直播]
[INFO 17:24:05] 停止

以下是下载的文件

| DATE/TIME | SIZE | FILENAME |
| ------------ | ---- | -------- |
| 02/13/2018  09:19 AM  |               0 | 491683-2018-2-13-9-19-59.flv |
| 02/13/2018  09:20 AM  |             170 | 491683-2018-2-13-9-19-59.xml |
| 02/15/2018  07:43 AM  |               0 | 491683-2018-2-15-7-43-2.flv |
| 02/15/2018  07:43 AM  |             170 | 491683-2018-2-15-7-43-2.xml |
| 02/17/2018  05:10 AM  |               0 | 491683-2018-2-17-5-10-52.flv |
| 02/17/2018  05:10 AM  |             170 | 491683-2018-2-17-5-10-52.xml |
| 02/18/2018  12:38 AM  |               0 | 491683-2018-2-18-0-38-21.flv |
| 02/18/2018  12:38 AM  |             170 | 491683-2018-2-18-0-38-21.xml |
| 02/18/2018  04:15 AM  |               0 | 491683-2018-2-18-4-15-11.flv |
| 02/18/2018  04:15 AM  |             170 | 491683-2018-2-18-4-15-11.xml |
| 02/19/2018  04:17 AM  |               0 | 491683-2018-2-19-4-17-53.flv |
| 02/19/2018  04:17 AM  |             170 | 491683-2018-2-19-4-17-53.xml |

**Comment by zyzsdy** [comment]
关于0字节视频的问题：
现在的版本不会自动删除任何文件，因为我不打算加入任何的分析文件内容的功能。所以没法知道是不是真的有在录视频。

【主播开始直播】是直播间里的一条特殊弹幕，不会显示出来，收到这条弹幕之后播放器准备接收直播视频，但是可能真正的直播并未开始，此时就会生成一个0字节视频和对应的空弹幕文件（空弹幕文件为170字节，内容是xml头和必要的描述信息）。

至于主播实际上有播放内容但是没有录到的情况，我这里无法复现，暂且认为它是正常的。
过些时间我会重新分析它的特殊弹幕内容，看看是不是因为定义有什么修改导致的。

**Comment by huqinpku** [comment]
我认为直播是确实开始了的，有两个原因，a 每次直播都有相应的直播结束记录， 而且每次直播时间都是1-3小时； b 我后来查看了直播页面，上面有之前一次直播末尾处的弹幕信息，可以确认直播确实存在。

**Comment by huqinpku** [comment]
会不会因为我在国外延迟比较大，接收到直播开始弹幕之后没有立刻收到视频流，超时了所以没有录上？

**Comment by Sofronio** [comment]
我也是同样的问题，应该是没有下载。而直播肯定开始了，因为是我自己在直播。
![qq 20180625015013](https://user-images.githubusercontent.com/11464550/41821907-23d1b0ba-781a-11e8-8b59-add22d25a0df.png)

**Comment by loveritsu929** [comment]
我也是在国外，浏览器直接打开bilibili直播间会无限loading的那种高ping战士
唯一一次录制成功是开了ss挂日本代理，其他都是0字节文件，可能真的跟延迟有关？

[INFO 09:59:07] 开始解析弹幕服务器
[INFO 09:59:13] 解析弹幕服务器地址成功：livecmt-2.bilibili.com
[INFO 11:06:16] [主播开始直播]
[INFO 11:06:18] 地址解析成功：https://qn.live-play.acgvideo.com/live-qn/213190/live_539998_8513862.flv?wsSecret=546dc872a923f30a5bb783b7f09dca76&wsTime=1532619379
[INFO 11:06:18] 下载地址已更新。
[INFO 16:10:41] [主播结束直播]
[INFO 19:16:07] 停止

**Comment by zyzsdy** [comment]
确认有时候CDN卡住后会无法下载视频流。这个不是本工具的问题，如果希望解决达到完全无人干预自动录制只有加入重试系统了。

目前还没有这个打算。今后可能先会在隔壁项目[biliroku-lite](https://github.com/zyzsdy/biliroku-lite)里加，如果好用了会往这边迁移。
