### ISSUE TITLE
Please use new api to get play url

### ISSUE THREAD

**Issue by kkocdko** [zyzsdy/biliroku#28]
Old api with many problems (such as long waitting). Please use new api:

```
api.live.bilibili.com/room/v1/Room/playUrl?cid={{LongRoomId}}&quality={{Quality}}&platform={{Platform}}
```

**Comment by zyzsdy** [comment]
Thanks for your Issue!
I have noticed this change and will fix it after I have spare time.

Also welcome pr.

**Comment by zyzsdy** [comment]
done. (b5978e6)
