### ISSUE TITLE
反馈点问题 ，比如直播中但总是检查出未直播？

### ISSUE THREAD

**Issue by y888** [zyzsdy/biliroku#3]
1总是反复点击“停止”和“开始” 才能开始录制。“自动开始”从来没有成功过！（win2012和win10下都试了结果一致）

2希望能添加，使用代理的选项。（海外用户挂国内的代理可能会好？）

**Comment by zyzsdy** [comment]
未直播的问题最近反馈了不少，猜测可能是B站修改了直播流传输的一些方式？

自动开始功能依赖正确连接弹幕服务器，并能收到正确的弹幕。由于B站api的修改最近这里确实出了很多问题（必须跟着B站api一起改才行）。

不过这些问题无论是复现还是定位都需要大量的时间，现在的我有点无力。所以只能

**跪求Pull Request！！！**

增加代理这个版本不考虑，这个功能就留待下个大版本吧。

**Comment by y888** [comment]
一起跪求，一起跪等。。。。除了捐款啥都不会。

**Comment by y888** [comment]
没必要自杀阿，囧。现在只能粗暴的使用屏幕录像了

**Comment by zyzsdy** [comment]
不是自杀。被DDOS了，欠了CDN公司2500块钱，我还不起，被封号了。

**Comment by zyzsdy** [comment]
不带自动更新的版本见[Tag 1.4.3](https://github.com/zyzsdy/biliroku/releases/tag/1.4.3)

**Comment by lautis0503** [comment]
我从这个月起也开始出现这个情况，已经开始直播但是检测出未直播

**Comment by lautis0503** [comment]
本issue与用户的网络状况有关，CheckStreaming仅等待了两秒，像我现在的网络状况基本需要5-10秒才能接收到视频流。建议加载较慢的自行更改编译
