### ISSUE TITLE
录制视频的大小不正常

### ISSUE THREAD

**Issue by TSStudio** [zyzsdy/biliroku#30]
![image](https://user-images.githubusercontent.com/30061150/55668661-88391f00-589f-11e9-9e8e-432f4c501899.png)
像这样一个直播，码率为6000，可是运行了接近10分钟，才只有1.01MB
且视频打开后，是断断续续的，不是完整视频

**Comment by LidoCKT** [comment]
你网的问题

**Comment by zyzsdy** [comment]
如动动所说的确你网的问题。B站用的flv分发是这样的了，对网络很敏感，丢包什么的都录不好。

另外这里显示的码率不一定是真正的码率。

顺便一提如果你想用这个工具录付费直播，劝你放弃了，录不到的 By Design。


对于网络问题引起的断流目前没有什么比较好的解决方案。现在尽量以保存下更多的数据作为目标。之后的版本会加入自动判断是不是断流然后自动重试的方案。
