### ISSUE TITLE
BiLiRoku的bug

### ISSUE THREAD

**Issue by Mifan-T** [zyzsdy/biliroku#31]
在BiLiRoku中输入的直播间ID过长会导致直播间无法删除
![image](https://user-images.githubusercontent.com/49829769/56473116-31d00100-6499-11e9-8a71-dc1bb518a1d9.png)

**Comment by zyzsdy** [comment]
emmmmmmmmmm

是我错了。

---------

BUG已确认，感谢您的反馈！

1. 未对填入的内容进行有效性检查。
2. UI元素重叠位置不合理，导致遮挡删除按钮。

**Comment by Mifan-T** [comment]
麻烦大佬了!
