### ISSUE TITLE
算是一个小问题吧

### ISSUE THREAD

**Issue by aliofwind** [zyzsdy/biliroku#33]
就是文件名变量的日期时间不会自动补0占两位，不加-的话会出现使用{H}{m}{s}三个变量，结果出来的文件名却是20151这种只有4位数字的时间，这个时候就比较难直接分辨是20:15:01或者是20:01:51开始录制的情况。日期方面还好，只有在1月11月12月的时候会混淆，比如2019112，直观上看是2019年1月12日和2019年11月2日都有可能

**Comment by zyzsdy** [comment]
未来版本考虑添加{HH}之类的变量支持前补0

**Comment by zyzsdy** [comment]
#39
