### ISSUE TITLE
大佬有计划加入把视频分段保存吗？

### ISSUE THREAD

**Issue by peqing** [zyzsdy/biliroku#37]
其实我想说的是大佬有计划做虎牙直播的录制工具吗？我用IDM可以获取下载链接，但是下载下来文件20多GB，不能分段，用视频工具分割基本内容出现问题。

**Comment by zyzsdy** [comment]
你需要了解一些视频文件的基础概念，比如IDR帧、帧率、可变帧率
这些都会影响视频的切割。

对于超大视频的切割的，一个大内存的电脑也是必要的。

但是对于一个视频保存/下载工具来说，我认为切割视频是对视频的破坏，这不符合我的哲学。
