### ISSUE TITLE
录制时间增长CPU占用会无故增加。

### ISSUE THREAD

**Issue by zyzsdy** [zyzsdy/biliroku#4]
理论上来说应该一直保持一个值左右不变的。

现在我有几个猜测：

1.  B站修改了直播flv的结构，导致mediainfo消耗上升。

2. B站修改了下载时的http连接方式，导致资源消耗在HttpClient上

3. 新版Windows对某个部分造成的修改导致（可能性不高）。

不过我放假前没时间查问题，这种找一次问题就要几个小时的。等我寒假之后再来看吧。

**跪求Pull Request**

**Comment by lautis0503** [comment]
之前下载安装的版本，录像三个多小时后占用CPU约26%
Win7 x64 + VS 2015 + .Net 4.6.2 自编译版本，连续录像一个多小时后占用约26%（之前录像两小时后因出现#6情况，停止再开始一次），三个多小时后占用约50%。停止录像后CPU占用率依旧不降。
二次测试，两个多小时后占用50%，定位为两个clr.dll!SetRuntimeInfo线程各占用25%

**Comment by lautis0503** [comment]
占用CPU的线程：
Thread:
clr.dll!SetRuntimeInfo+0xed90

Stack:
ntoskrnl.exe!KeWaitForMultipleObjects+0xc0a
ntoskrnl.exe!KeAcquireSpinLockAtDpcLevel+0x732
ntoskrnl.exe!KeWaitForMutexObject+0x19f
ntoskrnl.exe!PoStartNextPowerIrp+0xba4
ntoskrnl.exe!PoStartNextPowerIrp+0x1821
ntoskrnl.exe!PoStartNextPowerIrp+0x1a97
MediaInfo.dll!MediaInfo_Info_Version+0xcccba
MediaInfo.dll!MediaInfo_Info_Version+0x4cc39
MediaInfo.dll!MediaInfo_Info_Version+0x4c349
MediaInfo.dll!MediaInfo_Info_Version+0x4b2bc
MediaInfo.dll!MediaInfo_Info_Version+0x4997d
MediaInfo.dll!MediaInfo_Info_Version+0x499a8
MediaInfo.dll+0x1440
MediaInfo.dll!MediaInfo_Info_Version+0x1c084

MediaInfo的使用有问题？

**Comment by lautis0503** [comment]
更新最新的0.7.91版本MediaInfo后编译使用，录制8.5小时，CPU占用率最多到2%。
所以可能是MediaInfo早期版本的一个bug，测试无误后再pr。

**Comment by zyzsdy** [comment]
感谢！！
居然是mediainfo这么占cpu。。。

**Comment by lautis0503** [comment]
同时开启MediaInfoLib升级前后两个版本录制对比，四小时后旧版占用27%CPU，新版2%，应该没错。已pr
