### ISSUE TITLE
时间相关

### ISSUE THREAD

**Issue by Toxiad** [zyzsdy/biliroku#40]
下载的文件时间轴显示不正确。
因UI的时间是从文件读的,故UI的时间显示也不正确。

**Comment by zyzsdy** [comment]
此为预期行为
下载器不会干涉视频内部结构

**Comment by Toxiad** [comment]
> 此为预期行为
> 下载器不会干涉视频内部结构

感谢回复。那样的话是服务器给的头就不对么?

**Comment by zyzsdy** [comment]
> 感谢回复。那样的话是服务器给的头就不对么?

播主推上去的流就不对。
一般来说重封装一遍就可以修复了。

原始时间戳信息对后期处理的时候可能有帮助，尤其是推流为vfr的时候。故biliroku不会帮你自动重封装。这不在设计范围内。
