### ISSUE TITLE
无法录制弹幕，弹幕文件保持166或170字节

### ISSUE THREAD

**Issue by Maple0512** [zyzsdy/biliroku#41]
右侧日志：
开始解析弹幕服务器
地址解析成功
解析XML失败：意外的 DTD 声明。 第 1 行，位置 9。

弹幕文件170字节只有开头：
<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>0</chatid><mission>0</mission><maxlimit>0</maxlimit><source>k-v</source></i>
166字节的：
<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>0</chatid><mission>0</mission><maxlimit>0</maxlimit><source>k-v</source>

**Comment by zyzsdy** [comment]
感谢Issue。已确认问题，紧急修复中。

原有API已经无法使用。
现API如下：https://api.live.bilibili.com/room/v1/Danmu/getConf?room_id={_LoogRoomId}

**Comment by zyzsdy** [comment]
fixed on bc1bfe3

**Comment by Maple0512** [comment]
赞美大佬！超级感谢！
