### ISSUE TITLE
UI:输入字符长度问题

### ISSUE THREAD

**Issue by Toxiad** [zyzsdy/biliroku#44]
刷新间隔与检测超时输入框被允许输入过长数字导致程序崩溃。。
可为输入框设置`MaxLength`属性解决这一问题。

**Comment by Toxiad** [comment]
错误发生后程序无法再次启动,据测试原因为注册表值被修改为错误的值。
可在读取注册表时验证数据正确性。

**Comment by zyzsdy** [comment]
感谢报告，问题已确认。

使用`int.TryParse(string, out int)`替代`int.Parse(string)`来解决这个问题。
