### ISSUE TITLE
win10无法打开

### ISSUE THREAD

**Issue by xss9626** [zyzsdy/biliroku#45]
win10在点击”仍要运行”后打不开主界面，
之前的版本设置了直播监控刷新频率0.1s，不知道是否与这个有关

**Comment by Toxiad** [comment]
可能是设置的问题，把注册表相应键值改回去试试

**Comment by xss9626** [comment]
不知道该怎么改。。。。。。

**Comment by Toxiad** [comment]
看代码应该是software/biliroku

**Comment by xss9626** [comment]
解决了，谢谢

**Comment by zyzsdy** [comment]
与 #44 是同一问题。设计上刷新时间和超时两个框都只能填写整数，但是程序未对用户输入进行检测和过滤。
