### ISSUE TITLE
视频流解析失败，请问我改怎么做？

### ISSUE THREAD

**Issue by HundunLu** [zyzsdy/biliroku#46]
![image](https://user-images.githubusercontent.com/19450598/65390847-ddf17d00-dd94-11e9-9f95-c52fb3fd012f.png)

**Comment by Toxiad** [comment]
试了一下,没发现问题。重试一下看看?

**Comment by zyzsdy** [comment]
视频流地址解析失败这个错误提示表示biliroku访问playurl API时，B站服务器返回非JSON格式的错误信息。考虑到昨天B站CDN出现一些不稳定情况，可能是您所在的网络环境无法正常连接所致，一般来说稍等重试即可。

如果仍有问题请重新打开本issue。

**Comment by HundunLu** [comment]
已经确定是我网络，问题，但是我其他使用都是正常的，请问有哪些方法可以修正。我已经网络重置过了。

**Comment by zyzsdy** [comment]
https://api.live.bilibili.com/room/v1/Room/playUrl?cid=97582

你试试你直接浏览器打开这个有没有报错。

**Comment by HundunLu** [comment]
![image](https://user-images.githubusercontent.com/19450598/65737813-58622a00-e112-11e9-9fc7-60cf358ccaab.png
麻烦你了，我这方面并不懂
