### ISSUE TITLE
关于下载视频清晰度选择的问题

### ISSUE THREAD

**Issue by zyzsdy** [zyzsdy/biliroku#49]
#43 曾经做过一个修改，把参数中的quality=0改为quality=4
按照之前的API猜测，quality=4对应原画画质。这样可强制下载原画。

但是在对最近直播的观测中发现一些问题。

1. quality参数可能已经被弃用。
![image](https://user-images.githubusercontent.com/5925733/66714430-6342dd00-ede9-11e9-9c86-b0657407942c.png)
如上图，quality可选项只有3个，但是qn选项有5个，观察播放器可见实际使用的是5个清晰度。进行切换清晰度选择，浏览器发送的请求也是使用qn=10000这样的参数。因此我判断quality已弃用，仅保留作兼容性用途，应使用qn来调整质量。

2. qn=0返回默认清晰度，但是默认清晰度不一定是最高清晰度。比如上图，在qn=0时实际按照qn=400返回，而不是qn=10000。

3. qn的数字理论上和画质呈线性关系，但是经过观察，可能最好画质不一定出现在qn最大的流里面。反倒是qn=0一般固定返回最好画质。

综上，之后版本的biliroku会将 #43 的修改再次改为qn=0（最早是quality=0，#43 修改成了quality=4）。

在更远期的版本中，将提供选项可供用户调整默认下载的清晰度，以解决问题3提到的靠qn数字无法判断最好画质的问题。

**Comment by lautis0503** [comment]
第三点存疑，测试的B站直播间，原画是用qn=10000获取的，应该就是最高画质。

**Comment by zyzsdy** [comment]
> 第三点存疑，测试的B站直播间，原画是用qn=10000获取的，应该就是最高画质。

第三点确实存疑，上述是我事后听群友的报告得知。

我的分析是B站在那次直播中启用了“蓝光”画质，按照1080p码率4000k进行转码。但是原始推流可能并没有这么高，比如只有3500k，这就造成了蓝光画质数据上看起来更好的假象。实际上还是应该下载原画。
