### ISSUE TITLE
未开播状态下挂机，直播开始后程序停止工作

### ISSUE THREAD

**Issue by lautis0503** [zyzsdy/biliroku#5]
RT，1.4.3版本，更新说明中似乎有修复过，但似乎无论挂机时间长短，都是如此。

**Comment by lautis0503** [comment]
Windows 7 SP1 x64 + VS2015 + .Net 4.6.2 自编译版本功能正常
PS: 只正常了一次

**Comment by lautis0503** [comment]
版本1，1.4.4版本去除自动更新代码，开始录制四分钟后直播开始，程序停止工作。
版本2，将版本1加上Revert#2，同样开始录制四分钟后直播开始，程序工作正常。
应当是那个pr的代码有点问题。
之后再测试长时间挂机的情况。

**Comment by zyzsdy** [comment]
感谢测试，#2 的代码可能引入了一些我没有发现的bug。如果你能稳定复现，希望提供更多的停止工作时的报错信息。因为我本地测试是没有问题的。

#2 主要修复的问题是经过超长时间的挂机，导致下载地址被更新过了，这时候启动录制自然会下载失败（因为下载了一个不存在的地址）。
这个地址是跟随直播码变化的，如果主播的直播码不变，这个地址也不会变。

**Comment by lautis0503** [comment]
程序停止工作后用VS调试的信息

IOException was unhandled

An unhandled exception of type 'System.IO.IOException' occurred in mscorlib.dll

Additional information: The process cannot access the file '***********.xml' because it is being used by another process.

**Comment by lautis0503** [comment]
程序停止工作后的VS调试信息

System.IO.IOException was unhandled

Message: An unhandled exception of type 'System.IO.IOException' occurred in mscorlib.dll

Additional information: The process cannot access the file '*************.xml' because it is being used by another process.

直播开始后的弹幕文件被占用，原因不明。测试时无法稳定复现，但以往使用几乎没有正常过。

**Comment by lautis0503** [comment]
再次测试的错误信息

System.InvalidOperationException was unhandled

Message: An unhandled exception of type 'System.InvalidOperationException' occurred in mscorlib.dll

Additional information: The stream is currently in use by a previous operation on the stream.

~~似乎挂机大约五分钟之内程序工作是正常的。~~

直接原因：程序显示了两个开始直播的信息，开启了两个线程同时获取视频数据以及写文件，致使其中一个读写视频流和文件失败，程序异常退出。

所有版本均有该问题，偶尔正常工作是由于其中一个线程较慢，另一线程已设置变量为录制中，才没有出现竞争。（之前的Revert#2正常为偶然）

**Comment by lautis0503** [comment]
Biliroku会收到两条LiveStart数据，程序运行太快会导致两个线程同时写文件或读取视频流，所以随便改了点代码，忽略第二条LiveStart

**Comment by zyzsdy** [comment]
LiveStart确实会发送两条，但是实际上是这样的。
当你在直播页面上启动直播的时候会触发一条LiveStart，在服务器接收到推流的时候会触发第二条LiveStart。所以实际上是需要忽略第一条消息。

**Comment by zyzsdy** [comment]
我在 983d939 中尝试改了一下。
