### ISSUE TITLE
直播结束后会产生很多空的文件，只能手动停止

### ISSUE THREAD

**Issue by bojiwama** [zyzsdy/biliroku#51]
![Snipaste_2019-12-08_16-23-36](https://user-images.githubusercontent.com/33753242/70386755-73d19700-19d7-11ea-86a2-68f06dbd1ed7.png)

**Comment by zyzsdy** [comment]
暂时不会解决该问题。直播结束会返回自动监测开播状态，如果不需要请手工关闭。
