### ISSUE TITLE
长时间录制后，程序卡在某一秒，不能继续录制

### ISSUE THREAD

**Issue by lautis0503** [zyzsdy/biliroku#6]
似乎和 #2 有关，下载到5:36:01卡住了，文件长度为3.50G，网络正常，重新录制正常

**Comment by lautis0503** [comment]
不定期出现这种情况，有时候仅录制了三四十分钟也会中断

**Comment by zyzsdy** [comment]
我猜可能和#4也有关？

**Comment by lautis0503** [comment]
近期除网络异常外，不再出现该问题，看来是还是#4的原因
