### ISSUE TITLE
错误&&建议

### ISSUE THREAD

**Issue by banned2054** [zyzsdy/biliroku#60]
问题：1.时录制几分钟，视屏容量就不再增大了，需要手动断开录制。
           2.录制视频有空字节文件。
建议：添加软件后台运行功能，全天候运行软件容易误关。

**Comment by JasiAmu** [comment]
问题1我也遇到了，观察了一下info，发现是视频地址更新了，但是软件还是在继续之前的那个地址，所以文件大小没有变化，手动断开再录制是又重新获取了地址。希望大佬能够解决这个问题
