### ISSUE TITLE
能不能实现只录制音频+弹幕？

### ISSUE THREAD

**Issue by KOHAKUchan** [zyzsdy/biliroku#62]
RT，录制asmr的时候大多是一图流

**Comment by zyzsdy** [comment]
不能，目前B站直播使用同时传输音频和视频的hls方式，单独录制音频也不会更省流。

**Comment by jiangyun0327** [comment]
非常感谢您回复，我非常爱用这款程序。我提出这个问题，出发点是希望录制电台直播的文件大小能小点。
再次感谢。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zyzsdy/biliroku"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月14日(星期五) 上午10:32
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [zyzsdy/biliroku] 能不能实现只录制音频+弹幕？ (#62)





 
不能，目前B站直播使用同时传输音频和视频的hls方式，单独录制音频也不会更省流。
