### ISSUE TITLE
网络异常导致视频信息不正确

### ISSUE THREAD

**Issue by lautis0503** [zyzsdy/biliroku#8]
录制至45分多的时候网络异常，下载速度为零，几秒后恢复，由于开启了“等待主播推流后自动开始”，程序提示主播开始直播（没有检测当前状态？），并且录制时间跳到了10小时多，导致视频信息不正确。
PS: 视频播放器播放时会自动跳过中间这段，只要不手动跳到中间这段时间
PPS: 我好像提了太多issue

**Comment by zyzsdy** [comment]
这里正确的处理方式应该是结束当前录制。如果网络恢复，就自动开一个新录制。
不过现在程序没有检测网络连接的能力，暂时无法做到这一点。

**Comment by lautis0503** [comment]
网络较慢时开始录制，录制时间会以**已直播时长**为初始值，而后时间混乱，但播放视频时信息正确。某个很神奇的bug？
PS: 上次录制一会儿后网络异常，显示的录制时间似乎也是已直播时长

**Comment by zyzsdy** [comment]
录制时间显示的基准是mediainfo读到的视频持续时间。因为视频是流，怀疑mediainfo可能用了随flv发送的元数据。（不然没理由它能知道已直播时间啊，api里又没有。。。）

**Comment by 0x7A2C9E5D** [comment]
可以用yamdi修复时间轴

**Comment by zyzsdy** [comment]
本工具并没有自带修复时间轴的打算。如果有更好的解决方案我将重新开启该issue。
